name: Deploy

on:
  push:
    branches:
      - main
      - deployment

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v2
        with:
          node-version: '15'

      - run: npm install

      - run: npm run-script build

      - name: Minio Deploy
        uses: hkdobrev/minio-deploy-action@main
        with:
          endpoint: ${{ secrets.MINIO_STAGING_ENDPOINT }}
          access_key: ${{ secrets.MINIO_STAGING_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_STAGING_SECRET_KEY }}
          bucket: ${{ secrets.MINIO_STAGING_BUCKET }}
          source_dir: 'public'
          target_dir: '/'
